name: Build and Publish

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: Serilog.Sinks.WinForms.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore Serilog.Sinks.WinForms.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild Serilog.Sinks.WinForms.sln -p:Configuration=Release
